import type { User, Post, Product, Conversation, Message, Comment } from './types'

export const currentUser: User = {
  id: 'current-user',
  username: 'cryptotrader',
  displayName: 'Alex Morgan',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  bio: 'Full-time crypto trader | BTC maximalist | Sharing my journey',
  verified: true,
  followers: 12500,
  following: 892,
  postsCount: 347,
}

export const users: User[] = [
  {
    id: 'user-1',
    username: 'btc_whale',
    displayName: 'Bitcoin Whale',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Whale',
    bio: 'Accumulating since 2013. DCA is the way.',
    verified: true,
    followers: 89400,
    following: 156,
    postsCount: 1203,
    isOnline: true,
  },
  {
    id: 'user-2',
    username: 'defi_sarah',
    displayName: 'Sarah DeFi',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'DeFi researcher | Yield farming enthusiast | Not financial advice',
    verified: true,
    followers: 45200,
    following: 423,
    postsCount: 856,
    isOnline: true,
  },
  {
    id: 'user-3',
    username: 'chart_master',
    displayName: 'Chart Master',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chart',
    bio: 'Technical analysis expert | 10+ years in markets',
    verified: true,
    followers: 67800,
    following: 89,
    postsCount: 2341,
    isOnline: false,
  },
  {
    id: 'user-4',
    username: 'altcoin_hunter',
    displayName: 'Altcoin Hunter',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hunter',
    bio: 'Finding gems before they moon | Risk management first',
    verified: false,
    followers: 23100,
    following: 567,
    postsCount: 445,
    isOnline: true,
  },
  {
    id: 'user-5',
    username: 'crypto_newbie',
    displayName: 'Learning Larry',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Larry',
    bio: 'New to crypto, here to learn! Ask me questions.',
    verified: false,
    followers: 1250,
    following: 892,
    postsCount: 45,
    isOnline: false,
  },
  {
    id: 'user-6',
    username: 'nft_queen',
    displayName: 'NFT Queen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Queen',
    bio: 'NFT collector & creator | Art meets blockchain',
    verified: true,
    followers: 34500,
    following: 234,
    postsCount: 678,
    isOnline: true,
  },
]

export const posts: Post[] = [
  {
    id: 'post-1',
    author: users[0],
    content: '$BTC just broke through the $68k resistance level! This is huge. The weekly close above this level could confirm the bull run continuation. Remember when everyone was bearish at $16k? Those who DCA\'d are smiling now. Stay patient, stay humble.',
    createdAt: '2024-01-15T10:30:00Z',
    reactions: { rocket: 234, bullish: 567, bearish: 23, diamond: 189, fire: 345 },
    userReaction: null,
    commentsCount: 89,
    shares: 156,
    saved: false,
    type: 'text',
  },
  {
    id: 'post-2',
    author: users[1],
    content: 'New yield farming opportunity on Aave V3! Currently getting 12% APY on $ETH deposits with additional $AAVE rewards. The TVL has been growing steadily which is a good sign. Always DYOR and never invest more than you can afford to lose.',
    createdAt: '2024-01-15T09:15:00Z',
    reactions: { rocket: 156, bullish: 289, bearish: 45, diamond: 67, fire: 123 },
    userReaction: 'bullish',
    commentsCount: 45,
    shares: 78,
    saved: true,
    type: 'text',
  },
  {
    id: 'post-3',
    author: users[2],
    content: 'SIGNAL ALERT: $SOL looking bullish on the 4H chart. Clear breakout from the descending wedge with increasing volume. This could be the start of something big.',
    createdAt: '2024-01-15T08:00:00Z',
    reactions: { rocket: 445, bullish: 678, bearish: 89, diamond: 234, fire: 567 },
    userReaction: null,
    commentsCount: 234,
    shares: 345,
    saved: false,
    type: 'signal',
    signal: {
      ticker: 'SOL',
      action: 'buy',
      entry: 98.5,
      target: 125.0,
      stopLoss: 89.0,
    },
  },
  {
    id: 'post-4',
    author: users[3],
    content: 'Hot take: Most "altcoin gems" are just well-marketed projects with no real utility. Before investing in any altcoin, ask yourself:\n\n1. What problem does it solve?\n2. Who is the team behind it?\n3. What\'s the tokenomics?\n4. Is there real adoption?\n\nIf you can\'t answer these, you\'re gambling, not investing.',
    createdAt: '2024-01-15T07:30:00Z',
    reactions: { rocket: 89, bullish: 234, bearish: 156, diamond: 445, fire: 67 },
    userReaction: 'diamond',
    commentsCount: 178,
    shares: 234,
    saved: true,
    type: 'text',
  },
  {
    id: 'post-5',
    author: users[4],
    content: 'Just made my first $BTC purchase! Started with just $100 to learn how everything works. Any tips for a complete beginner? Should I also look into $ETH?',
    createdAt: '2024-01-15T06:45:00Z',
    reactions: { rocket: 567, bullish: 345, bearish: 12, diamond: 234, fire: 456 },
    userReaction: null,
    commentsCount: 312,
    shares: 45,
    saved: false,
    type: 'text',
  },
  {
    id: 'post-6',
    author: users[5],
    content: 'The NFT space is evolving beyond profile pictures. We\'re seeing real utility emerge: gaming assets, event tickets, membership passes, and more. The technology is here to stay, even if the hype cycles come and go. $BLUR $LOOKS',
    createdAt: '2024-01-15T05:30:00Z',
    reactions: { rocket: 123, bullish: 189, bearish: 78, diamond: 56, fire: 234 },
    userReaction: null,
    commentsCount: 67,
    shares: 89,
    saved: false,
    type: 'text',
  },
  {
    id: 'post-7',
    author: users[0],
    content: 'Unpopular opinion: The next bull run won\'t look like the previous ones. Institutional money changes everything. We\'ll see more gradual growth rather than parabolic moves. $BTC ETF approval was just the beginning.',
    createdAt: '2024-01-14T22:00:00Z',
    reactions: { rocket: 345, bullish: 456, bearish: 234, diamond: 567, fire: 123 },
    userReaction: null,
    commentsCount: 445,
    shares: 567,
    saved: false,
    type: 'text',
  },
  {
    id: 'post-8',
    author: users[2],
    content: 'Weekly market analysis thread:\n\n$BTC: Bullish above $65k, watching $70k resistance\n$ETH: Consolidating, ETF narrative building\n$SOL: Strong momentum, $100 is key level\n$AVAX: Recovery mode, needs volume\n\nOverall sentiment: Cautiously optimistic',
    createdAt: '2024-01-14T20:00:00Z',
    reactions: { rocket: 678, bullish: 890, bearish: 45, diamond: 345, fire: 456 },
    userReaction: 'rocket',
    commentsCount: 234,
    shares: 678,
    saved: true,
    type: 'text',
  },
]

export const comments: Record<string, Comment[]> = {
  'post-1': [
    {
      id: 'comment-1',
      author: users[1],
      content: 'Been holding since 2017, this feels different. Institutional adoption is real this time.',
      createdAt: '2024-01-15T10:45:00Z',
      likes: 45,
      liked: false,
    },
    {
      id: 'comment-2',
      author: users[3],
      content: 'I remember the FUD at $16k. Everyone was calling for $10k. Glad I kept buying.',
      createdAt: '2024-01-15T11:00:00Z',
      likes: 32,
      liked: true,
    },
  ],
  'post-3': [
    {
      id: 'comment-3',
      author: users[4],
      content: 'Great call! Already up 5% from this entry.',
      createdAt: '2024-01-15T08:30:00Z',
      likes: 23,
      liked: false,
    },
  ],
}

export const products: Product[] = [
  {
    id: 'product-1',
    seller: users[2],
    title: 'Pro Trading Signals - Monthly',
    description: 'Get daily trading signals with entry, target, and stop-loss levels for major cryptocurrencies.',
    longDescription: 'Our professional trading signals service provides you with carefully analyzed trading opportunities across major cryptocurrency pairs. Each signal includes detailed entry points, multiple take-profit targets, and strict stop-loss levels to manage your risk effectively.',
    price: 49.99,
    category: 'signals',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=300&fit=crop',
    rating: 4.8,
    reviewsCount: 234,
    sales: 1250,
    tags: ['BTC', 'ETH', 'Altcoins', 'Daily'],
    performance: {
      winRate: 72,
      avgReturn: 15.5,
      totalTrades: 456,
    },
  },
  {
    id: 'product-2',
    seller: users[0],
    title: 'Bitcoin Accumulation Strategy Guide',
    description: 'Learn the DCA strategy that turned $500/month into a life-changing portfolio.',
    longDescription: 'This comprehensive guide walks you through the exact dollar-cost averaging strategy I\'ve used since 2013 to build a substantial Bitcoin position. Learn when to buy, how much to allocate, and how to stay disciplined during market volatility.',
    price: 29.99,
    category: 'strategies',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&h=300&fit=crop',
    rating: 4.9,
    reviewsCount: 567,
    sales: 3420,
    tags: ['Bitcoin', 'DCA', 'Long-term', 'Beginner'],
  },
  {
    id: 'product-3',
    seller: users[1],
    title: 'DeFi Yield Farming Masterclass',
    description: 'Complete course on maximizing yields in decentralized finance protocols.',
    longDescription: 'From liquidity pools to yield aggregators, this course covers everything you need to know about generating passive income in DeFi. Includes real examples, risk assessment frameworks, and step-by-step tutorials.',
    price: 149.99,
    category: 'courses',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=300&fit=crop',
    rating: 4.7,
    reviewsCount: 189,
    sales: 890,
    tags: ['DeFi', 'Yield', 'Advanced', 'Passive Income'],
  },
  {
    id: 'product-4',
    seller: users[2],
    title: 'Technical Analysis Indicator Pack',
    description: 'Custom TradingView indicators for crypto markets with alerts.',
    longDescription: 'A collection of 10 custom TradingView indicators specifically designed for cryptocurrency markets. Includes trend detection, momentum oscillators, and volume analysis tools with customizable alerts.',
    price: 79.99,
    category: 'tools',
    image: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=400&h=300&fit=crop',
    rating: 4.6,
    reviewsCount: 145,
    sales: 678,
    tags: ['TradingView', 'Indicators', 'Technical Analysis'],
  },
  {
    id: 'product-5',
    seller: users[3],
    title: 'Altcoin Research Template',
    description: 'The exact framework I use to evaluate new cryptocurrency projects.',
    longDescription: 'Stop relying on hype and start doing proper research. This Notion template includes checklists, scoring systems, and red flag indicators to help you evaluate any cryptocurrency project systematically.',
    price: 19.99,
    category: 'tools',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    rating: 4.5,
    reviewsCount: 89,
    sales: 1234,
    tags: ['Research', 'Altcoins', 'Due Diligence', 'Template'],
  },
  {
    id: 'product-6',
    seller: users[0],
    title: 'Crypto Tax Optimization Guide',
    description: 'Legal strategies to minimize your cryptocurrency tax burden.',
    longDescription: 'Navigate the complex world of crypto taxation with this comprehensive guide. Learn about tax-loss harvesting, holding periods, and jurisdiction-specific strategies to keep more of your gains.',
    price: 39.99,
    category: 'strategies',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop',
    rating: 4.4,
    reviewsCount: 78,
    sales: 456,
    tags: ['Tax', 'Legal', 'Optimization'],
  },
  {
    id: 'product-7',
    seller: users[1],
    title: 'Swing Trading Signals - Weekly',
    description: 'Weekly swing trade setups for mid-term positions in top 20 cryptocurrencies.',
    longDescription: 'Perfect for traders who can\'t monitor charts all day. Receive 3-5 high-quality swing trade setups every week with detailed analysis and risk management guidelines.',
    price: 29.99,
    category: 'signals',
    image: 'https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=400&h=300&fit=crop',
    rating: 4.3,
    reviewsCount: 156,
    sales: 789,
    tags: ['Swing Trading', 'Weekly', 'Top 20'],
    performance: {
      winRate: 65,
      avgReturn: 22.3,
      totalTrades: 234,
    },
  },
  {
    id: 'product-8',
    seller: users[2],
    title: 'Crypto Trading Bootcamp',
    description: '8-week intensive course from zero to profitable trader.',
    longDescription: 'A structured 8-week program that takes you from complete beginner to confident trader. Includes video lessons, live Q&A sessions, practice exercises, and a private community.',
    price: 299.99,
    category: 'courses',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop',
    rating: 4.9,
    reviewsCount: 312,
    sales: 567,
    tags: ['Bootcamp', 'Beginner', 'Comprehensive', 'Community'],
  },
]

export const conversations: Conversation[] = [
  {
    id: 'conv-1',
    participant: users[0],
    lastMessage: {
      id: 'msg-1',
      senderId: users[0].id,
      content: 'Great question! I think the key is consistency...',
      timestamp: '2024-01-15T10:30:00Z',
      read: false,
    },
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    participant: users[1],
    lastMessage: {
      id: 'msg-2',
      senderId: 'current-user',
      content: 'Thanks for the DeFi tips, really helpful!',
      timestamp: '2024-01-15T09:15:00Z',
      read: true,
    },
    unreadCount: 0,
  },
  {
    id: 'conv-3',
    participant: users[2],
    lastMessage: {
      id: 'msg-3',
      senderId: users[2].id,
      content: 'The signal I posted yesterday hit the first target!',
      timestamp: '2024-01-14T22:00:00Z',
      read: false,
    },
    unreadCount: 1,
  },
  {
    id: 'conv-4',
    participant: users[3],
    lastMessage: {
      id: 'msg-4',
      senderId: 'current-user',
      content: 'What do you think about the new project?',
      timestamp: '2024-01-14T18:30:00Z',
      read: true,
    },
    unreadCount: 0,
  },
  {
    id: 'conv-5',
    participant: users[5],
    lastMessage: {
      id: 'msg-5',
      senderId: users[5].id,
      content: 'Check out this NFT collection!',
      timestamp: '2024-01-14T15:00:00Z',
      read: true,
    },
    unreadCount: 0,
  },
]

export const messages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      senderId: 'current-user',
      content: 'Hey! I loved your post about DCA. How do you stay disciplined during bear markets?',
      timestamp: '2024-01-15T10:00:00Z',
      read: true,
    },
    {
      id: 'msg-1-2',
      senderId: users[0].id,
      content: 'Thanks for reaching out! The key is having a plan before the bear market hits.',
      timestamp: '2024-01-15T10:15:00Z',
      read: true,
    },
    {
      id: 'msg-1-3',
      senderId: users[0].id,
      content: 'I set up automatic purchases so I don\'t have to make emotional decisions.',
      timestamp: '2024-01-15T10:20:00Z',
      read: true,
    },
    {
      id: 'msg-1-4',
      senderId: 'current-user',
      content: 'That makes sense. Do you ever adjust the amounts?',
      timestamp: '2024-01-15T10:25:00Z',
      read: true,
    },
    {
      id: 'msg-1-5',
      senderId: users[0].id,
      content: 'Great question! I think the key is consistency...',
      timestamp: '2024-01-15T10:30:00Z',
      read: false,
    },
  ],
  'conv-2': [
    {
      id: 'msg-2-1',
      senderId: users[1].id,
      content: 'Hey! Saw you were interested in yield farming. Happy to help!',
      timestamp: '2024-01-15T08:00:00Z',
      read: true,
    },
    {
      id: 'msg-2-2',
      senderId: 'current-user',
      content: 'Yes! I\'m trying to understand impermanent loss better.',
      timestamp: '2024-01-15T08:30:00Z',
      read: true,
    },
    {
      id: 'msg-2-3',
      senderId: users[1].id,
      content: 'IL is basically the difference between holding tokens vs providing liquidity. Let me explain...',
      timestamp: '2024-01-15T09:00:00Z',
      read: true,
    },
    {
      id: 'msg-2-4',
      senderId: 'current-user',
      content: 'Thanks for the DeFi tips, really helpful!',
      timestamp: '2024-01-15T09:15:00Z',
      read: true,
    },
  ],
  'conv-3': [
    {
      id: 'msg-3-1',
      senderId: 'current-user',
      content: 'Just entered the SOL trade based on your signal!',
      timestamp: '2024-01-14T20:00:00Z',
      read: true,
    },
    {
      id: 'msg-3-2',
      senderId: users[2].id,
      content: 'Nice! Remember to set your stop loss.',
      timestamp: '2024-01-14T20:30:00Z',
      read: true,
    },
    {
      id: 'msg-3-3',
      senderId: users[2].id,
      content: 'The signal I posted yesterday hit the first target!',
      timestamp: '2024-01-14T22:00:00Z',
      read: false,
    },
  ],
}

export const stories = [
  {
    id: 'story-1',
    title: 'How Bitcoin ETFs Changed Retail Sentiment',
    excerpt:
      'The recent ETF approvals shifted market dynamics and brought new capital — here’s what traders should watch next.',
    image: 'https://images.unsplash.com/photo-1611672841973-5f6f9f1a3b8c?w=800&h=600&fit=crop',
    author: users[0],
    publishedAt: '2024-05-01T08:00:00Z',
    readingTime: '4 min',
  },
  {
    id: 'story-2',
    title: 'DeFi Trends: Where Yield Is Going in 2024',
    excerpt: 'Yield strategies are evolving. From structured products to novel staking, learn which ideas are gaining traction.',
    image: 'https://images.unsplash.com/photo-1618534694758-11b2b1e7b8c2?w=800&h=600&fit=crop',
    author: users[1],
    publishedAt: '2024-04-20T10:00:00Z',
    readingTime: '6 min',
  },
  {
    id: 'story-3',
    title: 'NFTs With Real Utility: Beyond PFPs',
    excerpt: 'A closer look at NFT projects providing memberships, tickets, and on-chain utility that last beyond hype.',
    image: 'https://images.unsplash.com/photo-1605902711622-cfb43c44367b?w=800&h=600&fit=crop',
    author: users[5],
    publishedAt: '2024-03-15T12:00:00Z',
    readingTime: '5 min',
  },
]

export function formatTimeAgo(dateString: string): string {
  const date = new Date(dateString)
  const now = new Date()
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000)

  if (diffInSeconds < 60) return 'just now'
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}m ago`
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h ago`
  if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)}d ago`
  return date.toLocaleDateString()
}

export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

export function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

export function highlightTickers(text: string): string {
  return text.replace(/\$([A-Z]{2,10})/g, '<span class="text-emerald-500 font-semibold">$$$1</span>')
}
